import { Mission, MissionType, MissionStatus, Skin } from './types';

export const INITIAL_TOTAL_AREA = 150; // ha
export const LAND_CAPACITY_PER_DAY = 1.66; // 150ha / 90 days
export const PLANTING_CAPACITY_PER_DAY = 1.66; // 150ha / 90 days
export const NURSERY_CAPACITY_PER_DAY = 500; // bibit per hari per orang/monyet

export const MONTH_NAMES = [
  'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
  'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember',
];

/**
 * Skin diurutkan dari murah ke mahal. Makin tinggi tingkatnya, makin banyak
 * lapisan yang ditambahkan ke sprite: aksesori → efek → jubah/sayap → kilau.
 * tier 1 = seragam, 2 = aksesori, 3 = aksesori + efek, 4 = + jubah/sayap,
 * 5 = legenda (semua sekaligus).
 */
export const SKINS: Skin[] = [
  { id: 'classic', name: 'Classic Forester', description: 'Seragam standar rimbawan.', cost: 0, tier: 1,
    colors: { primary: '#8B4513', secondary: '#D2B48C', accent: '#3b1d08' } },
  { id: 'military', name: 'Forest Guard', description: 'Helm hijau, siap mengawal hutan.', cost: 3000, tier: 2,
    colors: { primary: '#5b6b2b', secondary: '#b5c48a', accent: '#1b1e0c' }, aksesori: ['helm_hijau'] },
  { id: 'manager', name: 'Safety Manager', description: 'Helm dan rompi oranye sang mandor.', cost: 4500, tier: 2,
    colors: { primary: '#8B4513', secondary: '#D2B48C', accent: '#3b1d08' }, aksesori: ['helm_oranye', 'rompi'] },
  { id: 'botanist', name: 'Elite Botanist', description: 'Topi daun ahli bibit.', cost: 6000, tier: 2,
    colors: { primary: '#2d5a27', secondary: '#9acd32', accent: '#0f2a0c' }, aksesori: ['topi_daun'] },
  { id: 'astro', name: 'Astro Ape', description: 'Kubah kaca — reklamasi di planet lain.', cost: 9000, tier: 3,
    colors: { primary: '#cbd5e1', secondary: '#f8fafc', accent: '#334155' }, aksesori: ['kubah'], efek: 'aura' },
  { id: 'cyber', name: 'Cyber Gorilla', description: 'Visor neon dari masa depan.', cost: 12000, tier: 3,
    colors: { primary: '#6d28d9', secondary: '#22d3ee', accent: '#1e1b4b' }, aksesori: ['visor'], efek: 'aura' },
  { id: 'samurai', name: 'Samurai Rimba', description: 'Kabuto merah bertanduk emas.', cost: 14000, tier: 3,
    colors: { primary: '#7f1d1d', secondary: '#fca5a5', accent: '#450a0a' }, aksesori: ['kabuto'], efek: 'bayangan' },
  { id: 'fire', name: 'Fire Monkey', description: 'Monyet api penjaga karhutla & penakluk titik panas.', cost: 16000, tier: 3,
    colors: { primary: '#b91c1c', secondary: '#fb923c', accent: '#3f0000' }, aksesori: ['api'], efek: 'api' },
  { id: 'ice', name: 'Frost Ape', description: 'Dingin, tenang, berkilau beku.', cost: 18000, tier: 3,
    colors: { primary: '#7dd3fc', secondary: '#f0f9ff', accent: '#0c4a6e' }, aksesori: ['es'], efek: 'es' },
  { id: 'money', name: 'Money Monkey', description: 'Monyet pengelola anggaran, RAB & pemegang koin emas.', cost: 20000, tier: 4,
    colors: { primary: '#059669', secondary: '#fef08a', accent: '#064e3b' }, aksesori: ['mahkota'], efek: 'kilau' },
  { id: 'shadow', name: 'Ninja Monkey', description: 'Bekerja dalam kegelapan.', cost: 22000, tier: 3,
    colors: { primary: '#27272a', secondary: '#52525b', accent: '#09090b' }, aksesori: ['masker'], efek: 'bayangan' },
  { id: 'golden', name: 'Golden Monkey', description: 'Berlapis emas murni, berkilau.', cost: 24000, tier: 4,
    colors: { primary: '#f59e0b', secondary: '#fef3c7', accent: '#78350f' }, aksesori: ['mahkota'], efek: 'kilau' },
  { id: 'king', name: 'The Forest King', description: 'Mahkota dan jubah penguasa rimba.', cost: 28000, tier: 4,
    colors: { primary: '#4c1d95', secondary: '#fde68a', accent: '#1e1b4b' }, aksesori: ['jubah', 'mahkota'], efek: 'aura' },
  { id: 'phoenix', name: 'Phoenix Ape', description: 'Sayap api yang tak pernah padam.', cost: 35000, tier: 4,
    colors: { primary: '#c2410c', secondary: '#fde047', accent: '#431407' }, aksesori: ['sayap_api', 'api'], efek: 'api' },
  { id: 'dragon', name: 'Naga Rimba', description: 'Tanduk dan sayap penjaga hutan purba.', cost: 42000, tier: 4,
    colors: { primary: '#14532d', secondary: '#86efac', accent: '#052e16' }, aksesori: ['sayap_naga', 'tanduk'], efek: 'aura' },
  { id: 'diamond', name: 'Diamond Primate', description: 'Kristal murni, memantulkan cahaya.', cost: 50000, tier: 5,
    colors: { primary: '#a5f3fc', secondary: '#ffffff', accent: '#164e63' }, aksesori: ['mahkota_kristal'], efek: 'kilau' },
  { id: 'legend', name: 'Rimbawan Legenda', description: 'Emas dan zamrud — hanya untuk yang menghijaukan 150 Ha.', cost: 75000, tier: 5,
    colors: { primary: '#ca8a04', secondary: '#bbf7d0', accent: '#422006' }, aksesori: ['sayap_emas', 'jubah', 'mahkota'], efek: 'kilau' },
];

export const INITIAL_MISSIONS: Mission[] = [
  {
    id: 'm1',
    title: 'Penataan Lahan (3 Bulan)',
    type: MissionType.LAND_PREP,
    description: 'Menata 150ha lahan kritis agar siap ditanami. Membutuhkan waktu dan ketelitian.',
    target: INITIAL_TOTAL_AREA,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 1000,
    capacityPerDay: LAND_CAPACITY_PER_DAY,
    durationDays: 90,
  },
  {
    id: 'm2_1',
    title: '1. Persiapan Pekerja',
    type: MissionType.NURSERY,
    description: 'Rekrut dan latih tim khusus persemaian.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 200,
    capacityPerDay: 2000,
    durationDays: 5,
  },
  {
    id: 'm2_2',
    title: '2. Media Tanam',
    type: MissionType.NURSERY,
    description: 'Mixing tanah topsoil, kompos, dan pasir.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 300,
    capacityPerDay: NURSERY_CAPACITY_PER_DAY,
    durationDays: 20,
    unlockedBy: ['m2_1'],
  },
  {
    id: 'm2_3',
    title: '3. Pengisian Polybag',
    type: MissionType.NURSERY,
    description: 'Mengisi polybag dengan media yang telah disiapkan.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 400,
    capacityPerDay: 400,
    durationDays: 25,
    unlockedBy: ['m2_2'],
  },
  {
    id: 'm2_6',
    title: '6. Penyemaian Benih',
    type: MissionType.NURSERY,
    description: 'Penanaman benih unggul Sengon ke tiap polybag.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 500,
    capacityPerDay: 800,
    durationDays: 12,
    unlockedBy: ['m2_3'],
  },
  {
    id: 'm2_7',
    title: '7. Pemeliharaan Rutin',
    type: MissionType.NURSERY,
    description: 'Penyiraman intensif pagi dan sore.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 450,
    capacityPerDay: 10000,
    durationDays: 1,
    unlockedBy: ['m2_6'],
  },
  {
    id: 'm2_10',
    title: '10. Sertifikasi Bibit',
    type: MissionType.NURSERY,
    description: 'Pemeriksaan akhir kesiapan bibit sebelum distribusi.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 800,
    capacityPerDay: 2500,
    durationDays: 4,
    unlockedBy: ['m2_7'],
  },
  {
    id: 'm3',
    title: 'Penanaman Masif',
    type: MissionType.PLANTING,
    description: 'Menanam seluruh bibit ke 150ha lahan yang sudah siap.',
    target: INITIAL_TOTAL_AREA,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 2500,
    capacityPerDay: PLANTING_CAPACITY_PER_DAY,
    durationDays: 90,
    unlockedBy: ['m1', 'm2_10'],
  },
];
