import { Mission, MissionType, MissionStatus, Skin } from './types';

export const INITIAL_TOTAL_AREA = 150; // ha
export const LAND_CAPACITY_PER_DAY = 1.66; // 150ha / 90 days
export const PLANTING_CAPACITY_PER_DAY = 1.66; // 150ha / 90 days
export const NURSERY_CAPACITY_PER_DAY = 500; // bibit per hari per orang/monyet

export const MONTH_NAMES = [
  'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
  'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember',
];

/**
 * Skin diurutkan dari murah ke mahal. Makin tinggi tingkatnya, makin banyak
 * lapisan yang ditambahkan ke sprite: aksesori → efek → jubah/sayap → kilau.
 * tier 1 = seragam, 2 = aksesori, 3 = aksesori + efek, 4 = + jubah/sayap,
 * 5 = legenda (semua sekaligus).
 */
export const SKINS: Skin[] = [
  { id: 'classic', name: 'Classic Forester', description: 'Seragam standar rimbawan.', cost: 0, tier: 1,
    colors: { primary: '#8B4513', secondary: '#D2B48C', accent: '#3b1d08' },
    sejarah: 'Seragam pertama yang dibagikan saat tim reklamasi dibentuk, ketika lahan bekas tambang masih berupa tanah merah terbuka.',
    filosofi: 'Semua pekerjaan besar dimulai dari seragam sederhana dan niat untuk hadir setiap hari.' },
  { id: 'military', name: 'Forest Guard', description: 'Helm hijau, siap mengawal hutan.', cost: 3000, tier: 2,
    colors: { primary: '#5b6b2b', secondary: '#b5c48a', accent: '#1b1e0c' }, aksesori: ['helm_hijau'],
    sejarah: 'Dipakai regu patroli yang menjaga tanaman muda dari ternak, api, dan pembalakan liar.',
    filosofi: 'Menanam itu sehari; menjaga itu bertahun-tahun.' },
  { id: 'manager', name: 'Safety Manager', description: 'Helm dan rompi oranye sang mandor.', cost: 4500, tier: 2,
    colors: { primary: '#8B4513', secondary: '#D2B48C', accent: '#3b1d08' }, aksesori: ['helm_oranye', 'rompi'],
    sejarah: 'Helm dan rompi oranye sang mandor yang memastikan setiap orang pulang dengan selamat.',
    filosofi: 'Target tidak ada artinya bila ada yang terluka. Keselamatan adalah pekerjaan pertama.' },
  { id: 'botanist', name: 'Elite Botanist', description: 'Topi daun ahli bibit.', cost: 6000, tier: 2,
    colors: { primary: '#2d5a27', secondary: '#9acd32', accent: '#0f2a0c' }, aksesori: ['topi_daun'],
    sejarah: 'Ahli persemaian yang hafal setiap bedeng, tahu kapan bibit haus dan kapan siap dipindah.',
    filosofi: 'Hutan yang kuat lahir dari bibit yang dirawat dengan sabar.' },
  { id: 'astro', name: 'Astro Ape', description: 'Kubah kaca — reklamasi di planet lain.', cost: 9000, tier: 3,
    colors: { primary: '#cbd5e1', secondary: '#f8fafc', accent: '#334155' }, aksesori: ['kubah'], efek: 'aura',
    sejarah: 'Kisah monyet yang membayangkan menghijaukan planet lain, karena lahan tandus di bumi sudah berhasil ia pulihkan.',
    filosofi: 'Bermimpilah jauh, tetapi mulailah dari lahan di depan mata.' },
  { id: 'cyber', name: 'Cyber Gorilla', description: 'Visor neon dari masa depan.', cost: 12000, tier: 3,
    colors: { primary: '#6d28d9', secondary: '#22d3ee', accent: '#1e1b4b' }, aksesori: ['visor'], efek: 'aura',
    sejarah: 'Lahir ketika laporan kertas berganti menjadi data, peta, dan foto bergeotag.',
    filosofi: 'Data yang rapi membuat kerja keras terlihat dan bisa dipercaya.' },
  { id: 'samurai', name: 'Samurai Rimba', description: 'Kabuto merah bertanduk emas.', cost: 14000, tier: 3,
    colors: { primary: '#7f1d1d', secondary: '#fca5a5', accent: '#450a0a' }, aksesori: ['kabuto'], efek: 'bayangan',
    sejarah: 'Penjaga yang memegang janji: PICA yang ia pegang selalu selesai sebelum tenggat.',
    filosofi: 'Disiplin adalah bentuk hormat pada tim.' },
  { id: 'fire', name: 'Fire Monkey', description: 'Monyet api penjaga karhutla & penakluk titik panas.', cost: 16000, tier: 3,
    colors: { primary: '#b91c1c', secondary: '#fb923c', accent: '#3f0000' }, aksesori: ['api'], efek: 'api',
    sejarah: 'Garda depan saat musim kemarau, orang pertama yang berlari ke titik panas.',
    filosofi: 'Api kecil dipadamkan hari ini; api besar dicegah sejak kemarin.' },
  { id: 'ice', name: 'Frost Ape', description: 'Dingin, tenang, berkilau beku.', cost: 18000, tier: 3,
    colors: { primary: '#7dd3fc', secondary: '#f0f9ff', accent: '#0c4a6e' }, aksesori: ['es'], efek: 'es',
    sejarah: 'Ia tetap tenang di tengah tekanan dan berkepala dingin saat semua orang panik.',
    filosofi: 'Keputusan terbaik lahir dari kepala yang dingin.' },
  { id: 'money', name: 'Money Monkey', description: 'Monyet pengelola anggaran, RAB & pemegang koin emas.', cost: 20000, tier: 4,
    colors: { primary: '#059669', secondary: '#fef08a', accent: '#064e3b' }, aksesori: ['mahkota'], efek: 'kilau',
    sejarah: 'Penjaga koin dan RAB; setiap rupiah tercatat dan bisa dipertanggungjawabkan.',
    filosofi: 'Anggaran yang jujur adalah fondasi kepercayaan.' },
  { id: 'shadow', name: 'Ninja Monkey', description: 'Bekerja dalam kegelapan.', cost: 22000, tier: 3,
    colors: { primary: '#27272a', secondary: '#52525b', accent: '#09090b' }, aksesori: ['masker'], efek: 'bayangan',
    sejarah: 'Bekerja tanpa sorotan: menyelesaikan tugas yang tidak dilihat orang, tetapi terasa hasilnya.',
    filosofi: 'Integritas adalah apa yang kamu lakukan saat tidak ada yang melihat.' },
  { id: 'golden', name: 'Golden Monkey', description: 'Berlapis emas murni, berkilau.', cost: 24000, tier: 4,
    colors: { primary: '#f59e0b', secondary: '#fef3c7', accent: '#78350f' }, aksesori: ['mahkota'], efek: 'kilau',
    sejarah: 'Penghargaan bagi yang konsisten: bukan sekali hebat, tetapi hadir dan melapor hari demi hari.',
    filosofi: 'Emas bukan bakat, tetapi kebiasaan yang diulang.' },
  { id: 'king', name: 'The Forest King', description: 'Mahkota dan jubah penguasa rimba.', cost: 28000, tier: 4,
    colors: { primary: '#4c1d95', secondary: '#fde68a', accent: '#1e1b4b' }, aksesori: ['jubah', 'mahkota'], efek: 'aura',
    sejarah: 'Mahkota bagi pemimpin yang membesarkan timnya, bukan dirinya sendiri.',
    filosofi: 'Raja rimba melayani hutannya.' },
  { id: 'phoenix', name: 'Phoenix Ape', description: 'Sayap api yang tak pernah padam.', cost: 35000, tier: 4,
    colors: { primary: '#c2410c', secondary: '#fde047', accent: '#431407' }, aksesori: ['sayap_api', 'api'], efek: 'api',
    sejarah: 'Bangkit dari lahan terbakar; kisah blok yang pernah gagal tanam lalu tumbuh kembali.',
    filosofi: 'Kegagalan adalah abu tempat tunas baru tumbuh.' },
  { id: 'dragon', name: 'Naga Rimba', description: 'Tanduk dan sayap penjaga hutan purba.', cost: 42000, tier: 4,
    colors: { primary: '#14532d', secondary: '#86efac', accent: '#052e16' }, aksesori: ['sayap_naga', 'tanduk'], efek: 'aura',
    sejarah: 'Penjaga hutan purba dalam cerita lama, yang terbangun ketika lahan kembali hijau.',
    filosofi: 'Kita meminjam hutan dari anak cucu.' },
  { id: 'diamond', name: 'Diamond Primate', description: 'Kristal murni, memantulkan cahaya.', cost: 50000, tier: 5,
    colors: { primary: '#a5f3fc', secondary: '#ffffff', accent: '#164e63' }, aksesori: ['mahkota_kristal'], efek: 'kilau',
    sejarah: 'Ditempa oleh tekanan panjang, seperti lahan keras yang akhirnya ditumbuhi tanaman.',
    filosofi: 'Tekanan membentuk ketangguhan.' },
  { id: 'legend', name: 'Rimbawan Legenda', description: 'Emas dan zamrud — hanya untuk yang menghijaukan 150 Ha.', cost: 75000, tier: 5,
    colors: { primary: '#ca8a04', secondary: '#bbf7d0', accent: '#422006' }, aksesori: ['sayap_emas', 'jubah', 'mahkota'], efek: 'kilau',
    sejarah: 'Hanya untuk mereka yang ikut menghijaukan 150 hektar; namanya diingat setiap pohon yang tumbuh.',
    filosofi: 'Warisan sejati adalah hutan yang tetap berdiri setelah kita pergi.' },
  // ---------- Skin Prestasi: tidak dijual, terbuka dari kerja (server/src/prestasi-aturan.ts) ----------
  { id: 'first_responder', name: 'First Responder', description: 'Pemeriksa pertama di titik api.', cost: 0, tier: 6, prestasi: true,
    colors: { primary: '#7c2d12', secondary: '#fdba74', accent: '#1c0a03' }, aksesori: ['helm_pemadam', 'rompi_reflektor', 'medali'], efek: 'api',
    sejarah: 'Ia yang pertama tiba di titik api dan memastikan apa yang terjadi di lapangan, sebelum asap menjadi kabar.',
    filosofi: 'Kecepatan memeriksa menyelamatkan hektar demi hektar.' },
  { id: 'pemburu_pica', name: 'Pemburu PICA', description: 'Sepuluh PICA ditutup sampai tuntas.', cost: 0, tier: 6, prestasi: true,
    colors: { primary: '#3f3f46', secondary: '#e7e5e4', accent: '#0c0a09' }, aksesori: ['topi_pemburu', 'kaca_pembesar', 'medali'], efek: 'kilau',
    sejarah: 'Ia memburu temuan sampai tuntas — mencari akar masalah, menindaklanjuti, mengunggah bukti — bukan sekadar mencatatnya.',
    filosofi: 'Masalah yang ditutup lebih berharga daripada seratus yang dicatat.' },
  { id: 'penyelamat_tim', name: 'Penyelamat Tim', description: 'Turun tangan menyelamatkan PICA telat rekan.', cost: 0, tier: 6, prestasi: true,
    colors: { primary: '#1d4ed8', secondary: '#bfdbfe', accent: '#0b1437' }, aksesori: ['jubah_merah', 'ikat_kepala', 'lambang_tolong'], efek: 'aura',
    sejarah: 'Saat PICA seorang rekan terlambat, ia turun tangan tanpa menunggu diminta, sampai temuan itu ditutup.',
    filosofi: 'Tim yang kuat tidak membiarkan anggotanya tertinggal.' },
  { id: 'fotografer', name: 'Fotografer Lapangan', description: 'Tiga puluh laporan berfoto di hari yang sama.', cost: 0, tier: 6, prestasi: true,
    colors: { primary: '#854d0e', secondary: '#fde68a', accent: '#291703' }, aksesori: ['baret', 'kamera'], efek: 'kilau',
    sejarah: 'Lensanya menjadi bukti: setiap laporan disertai gambar yang jujur, diambil di hari yang sama dengan kerjanya.',
    filosofi: 'Satu foto yang jujur mengalahkan seribu kata.' },
];

export const INITIAL_MISSIONS: Mission[] = [
  {
    id: 'm1',
    title: 'Penataan Lahan (3 Bulan)',
    type: MissionType.LAND_PREP,
    description: 'Menata 150ha lahan kritis agar siap ditanami. Membutuhkan waktu dan ketelitian.',
    target: INITIAL_TOTAL_AREA,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 1000,
    capacityPerDay: LAND_CAPACITY_PER_DAY,
    durationDays: 90,
  },
  {
    id: 'm2_1',
    title: '1. Persiapan Pekerja',
    type: MissionType.NURSERY,
    description: 'Rekrut dan latih tim khusus persemaian.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 200,
    capacityPerDay: 2000,
    durationDays: 5,
  },
  {
    id: 'm2_2',
    title: '2. Media Tanam',
    type: MissionType.NURSERY,
    description: 'Mixing tanah topsoil, kompos, dan pasir.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 300,
    capacityPerDay: NURSERY_CAPACITY_PER_DAY,
    durationDays: 20,
    unlockedBy: ['m2_1'],
  },
  {
    id: 'm2_3',
    title: '3. Pengisian Polybag',
    type: MissionType.NURSERY,
    description: 'Mengisi polybag dengan media yang telah disiapkan.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 400,
    capacityPerDay: 400,
    durationDays: 25,
    unlockedBy: ['m2_2'],
  },
  {
    id: 'm2_6',
    title: '6. Penyemaian Benih',
    type: MissionType.NURSERY,
    description: 'Penanaman benih unggul Sengon ke tiap polybag.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 500,
    capacityPerDay: 800,
    durationDays: 12,
    unlockedBy: ['m2_3'],
  },
  {
    id: 'm2_7',
    title: '7. Pemeliharaan Rutin',
    type: MissionType.NURSERY,
    description: 'Penyiraman intensif pagi dan sore.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 450,
    capacityPerDay: 10000,
    durationDays: 1,
    unlockedBy: ['m2_6'],
  },
  {
    id: 'm2_10',
    title: '10. Sertifikasi Bibit',
    type: MissionType.NURSERY,
    description: 'Pemeriksaan akhir kesiapan bibit sebelum distribusi.',
    target: 10000,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 800,
    capacityPerDay: 2500,
    durationDays: 4,
    unlockedBy: ['m2_7'],
  },
  {
    id: 'm3',
    title: 'Penanaman Masif',
    type: MissionType.PLANTING,
    description: 'Menanam seluruh bibit ke 150ha lahan yang sudah siap.',
    target: INITIAL_TOTAL_AREA,
    current: 0,
    status: MissionStatus.AVAILABLE,
    rewardXP: 2500,
    capacityPerDay: PLANTING_CAPACITY_PER_DAY,
    durationDays: 90,
    unlockedBy: ['m1', 'm2_10'],
  },
];
