/**
 * Pintasan ":nama" di penyunting memo (seperti :emoji: di Notion). Kata kunci
 * dalam bahasa Indonesia dan Inggris; cukup untuk catatan kerja lapangan.
 */

export interface Emoji { e: string; kata: string[] }

export const DAFTAR_EMOJI: Emoji[] = [
  { e: '😀', kata: ['senyum', 'senang', 'smile', 'grin'] },
  { e: '😂', kata: ['tawa', 'ketawa', 'lucu', 'joy', 'laugh'] },
  { e: '🙂', kata: ['senyum', 'ramah', 'slight'] },
  { e: '😉', kata: ['kedip', 'wink'] },
  { e: '😍', kata: ['suka', 'cinta', 'love', 'heart'] },
  { e: '🤔', kata: ['pikir', 'bingung', 'think', 'hmm'] },
  { e: '😮', kata: ['kaget', 'wow', 'heran'] },
  { e: '😢', kata: ['sedih', 'nangis', 'sad', 'cry'] },
  { e: '😡', kata: ['marah', 'angry'] },
  { e: '😴', kata: ['tidur', 'ngantuk', 'sleep'] },
  { e: '🥵', kata: ['panas', 'gerah', 'hot'] },
  { e: '🥶', kata: ['dingin', 'cold'] },
  { e: '👍', kata: ['oke', 'setuju', 'jempol', 'like', 'ok', 'thumbsup'] },
  { e: '👎', kata: ['tidak', 'tolak', 'dislike', 'thumbsdown'] },
  { e: '👏', kata: ['tepuk', 'bagus', 'clap', 'selamat'] },
  { e: '🙏', kata: ['terima', 'kasih', 'mohon', 'tolong', 'pray', 'thanks'] },
  { e: '💪', kata: ['semangat', 'kuat', 'kerja', 'muscle'] },
  { e: '🤝', kata: ['sepakat', 'kerjasama', 'deal', 'handshake'] },
  { e: '👋', kata: ['halo', 'hai', 'wave', 'hello'] },
  { e: '👀', kata: ['lihat', 'cek', 'mata', 'eyes', 'look'] },
  { e: '✅', kata: ['selesai', 'beres', 'centang', 'done', 'check'] },
  { e: '☑️', kata: ['ceklis', 'tugas', 'checkbox'] },
  { e: '❌', kata: ['salah', 'batal', 'gagal', 'x', 'cross'] },
  { e: '⚠️', kata: ['peringatan', 'awas', 'hati', 'warning'] },
  { e: '❗', kata: ['penting', 'seru', 'important'] },
  { e: '❓', kata: ['tanya', 'pertanyaan', 'question'] },
  { e: '💡', kata: ['ide', 'gagasan', 'idea', 'lampu'] },
  { e: '📌', kata: ['sematkan', 'pin', 'tanda'] },
  { e: '📍', kata: ['lokasi', 'titik', 'tempat', 'location'] },
  { e: '🗺️', kata: ['peta', 'map'] },
  { e: '📅', kata: ['tanggal', 'kalender', 'jadwal', 'calendar'] },
  { e: '⏰', kata: ['jam', 'alarm', 'waktu', 'tenggat', 'clock'] },
  { e: '⏳', kata: ['tunggu', 'proses', 'waiting'] },
  { e: '📝', kata: ['catatan', 'tulis', 'memo', 'note'] },
  { e: '📋', kata: ['daftar', 'papan', 'clipboard'] },
  { e: '📊', kata: ['grafik', 'data', 'laporan', 'chart'] },
  { e: '📈', kata: ['naik', 'tren', 'meningkat', 'up'] },
  { e: '📉', kata: ['turun', 'menurun', 'down'] },
  { e: '📎', kata: ['lampiran', 'klip', 'attachment'] },
  { e: '📁', kata: ['folder', 'berkas', 'arsip'] },
  { e: '📷', kata: ['foto', 'kamera', 'camera'] },
  { e: '📞', kata: ['telepon', 'telpon', 'phone'] },
  { e: '📣', kata: ['pengumuman', 'umumkan', 'announce'] },
  { e: '📦', kata: ['paket', 'barang', 'kirim', 'package'] },
  { e: '💰', kata: ['uang', 'biaya', 'dana', 'money', 'rab'] },
  { e: '🧾', kata: ['nota', 'kwitansi', 'struk', 'receipt'] },
  { e: '🔥', kata: ['api', 'panas', 'kebakaran', 'fire', 'hotspot'] },
  { e: '🧯', kata: ['pemadam', 'apar', 'extinguisher'] },
  { e: '🦺', kata: ['rompi', 'apd', 'k3', 'safety', 'vest'] },
  { e: '⛑️', kata: ['helm', 'apd', 'k3', 'helmet'] },
  { e: '🚧', kata: ['proyek', 'konstruksi', 'perbaikan', 'construction'] },
  { e: '🛠️', kata: ['alat', 'perbaikan', 'servis', 'tools'] },
  { e: '🔧', kata: ['kunci', 'perbaikan', 'wrench'] },
  { e: '⚙️', kata: ['pengaturan', 'mesin', 'gear'] },
  { e: '🚜', kata: ['traktor', 'alat', 'berat', 'tractor'] },
  { e: '🚚', kata: ['truk', 'angkut', 'kirim', 'truck'] },
  { e: '⛏️', kata: ['tambang', 'gali', 'pick', 'mining'] },
  { e: '🌱', kata: ['bibit', 'semai', 'tunas', 'nursery', 'seedling'] },
  { e: '🌳', kata: ['pohon', 'tanam', 'hutan', 'tree'] },
  { e: '🌲', kata: ['pinus', 'hutan', 'evergreen'] },
  { e: '🌿', kata: ['daun', 'tanaman', 'herb'] },
  { e: '🍃', kata: ['daun', 'angin', 'leaf'] },
  { e: '🌾', kata: ['padi', 'lahan', 'rice'] },
  { e: '💧', kata: ['air', 'siram', 'tetes', 'water'] },
  { e: '🌧️', kata: ['hujan', 'cuaca', 'rain'] },
  { e: '☀️', kata: ['cerah', 'matahari', 'sun'] },
  { e: '⛅', kata: ['berawan', 'cuaca', 'cloud'] },
  { e: '⚡', kata: ['petir', 'listrik', 'cepat', 'zap'] },
  { e: '🐒', kata: ['monyet', 'pokemonkey', 'monkey'] },
  { e: '🍌', kata: ['pisang', 'banana'] },
  { e: '🎯', kata: ['target', 'sasaran', 'tujuan'] },
  { e: '🏆', kata: ['juara', 'menang', 'trophy'] },
  { e: '⭐', kata: ['bintang', 'favorit', 'star'] },
  { e: '🎉', kata: ['rayakan', 'selamat', 'pesta', 'party'] },
  { e: '🚀', kata: ['luncur', 'cepat', 'rocket', 'mulai'] },
  { e: '🔒', kata: ['kunci', 'rahasia', 'pribadi', 'lock'] },
  { e: '🔑', kata: ['kunci', 'akses', 'key'] },
  { e: '🔔', kata: ['notifikasi', 'pengingat', 'bell'] },
  { e: '🔍', kata: ['cari', 'periksa', 'search'] },
  { e: '➡️', kata: ['kanan', 'lanjut', 'panah', 'arrow'] },
  { e: '⬅️', kata: ['kiri', 'kembali', 'panah'] },
  { e: '⬆️', kata: ['atas', 'naik', 'panah'] },
  { e: '⬇️', kata: ['bawah', 'turun', 'panah'] },
  { e: '🟢', kata: ['hijau', 'aman', 'lancar', 'green'] },
  { e: '🟡', kata: ['kuning', 'waspada', 'yellow'] },
  { e: '🔴', kata: ['merah', 'bahaya', 'red'] },
  { e: '❤️', kata: ['hati', 'cinta', 'heart'] },
  { e: '💯', kata: ['seratus', 'sempurna', 'hundred'] },
];

/** Emoji yang cocok dengan kueri (awal kata), paling banyak `maks`. */
export function cariEmoji(q: string, maks = 8): Emoji[] {
  const k = q.toLowerCase();
  return DAFTAR_EMOJI.filter((x) => x.kata.some((w) => w.startsWith(k))).slice(0, maks);
}
